### ISSUE TITLE
Missing package product 'CombineRex'

### ISSUE THREAD

**Issue by nikputnam** [npvisual/ToDoList-Redux#3]
This looks like such a valuable starting point for someone (like me) interested in adopting SwiftRex!  

I'd like to be able to 

```
git clone https://github.com/npvisual/ToDoList-Redux.git 
cd ToDoList-Redux
open ToDoList-Redux.xcodeproj
```

And hit the "Run" button...  but I get 

"Build Failed"
"Package Loading"
"Missing package product 'CombineRex'"

I tried to add `https://github.com/SwiftRex/SwiftRex.git` as a package dependency, but it says it already is one, and "CombineRex" does show up under "Frameworks, Libraries, and Embedded Content" under the "General" section of the Target setting panel in Xcode for the ToDoList-Redux target.  

I've done some React/Redux in js, and I've written some swift code, but I'm a relative newcomer to Xcode.  Any suggestions?  

(Xcode 12.4; MacOS 11.2.3)

Thanks!
Nik

**Comment by npvisual** [comment]
Hi @nikputnam , thanks for your feedback. I'll try and take a look tomorrow to see if I can fix this problem.

**Comment by luizmb** [comment]
Hi @nikputnam 

Thanks for reporting. I just created this PR (https://github.com/npvisual/ToDoList-Redux/pull/4) to fix it, but while @npvisual doesn't review you can try directly the branch FixBuild in order to test it.

**Comment by npvisual** [comment]
Thanks to @luizmb this should be working now. I will double check tomorrow as I don't have time today. Let me know if this is still not working for you.

**Comment by luizmb** [comment]
Probably thanks to me was broken in the first place... So I guess my karma is back to zero. :)

**Comment by nikputnam** [comment]
Thanks for the fast fix!
